mod canvas;
pub use canvas::Span;
mod engine;
pub use engine::{Highlighted, Highlighter};
mod injection;
mod lines;
mod overrides;
pub use overrides::{Overrides, strip_overrides};
mod library;
pub use library::*;
