name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: blacksmith-4vcpu-ubuntu-2404
            target: x64
          - image: blacksmith-4vcpu-ubuntu-2404-arm
            target: arm64
          - image: blacksmith-6vcpu-macos-latest
            target: arm64
          - image: blacksmith-4vcpu-windows-2025
            target: x64
          # if needed: blacksmith currently doesn't have windows runners
          # - image: windows-11-arm
          #  target: arm64
    runs-on: ${{ matrix.image }}
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: ${{ matrix.target }}
          tool-mdbook: true
      - uses: Pistonight/mono-dev/actions/rust-xplat@main
        with:
          arch: ${{ matrix.target }}
          binary: mdbook-nvim-treesitter
         
          pre-task: test
          # ensure the example book builds
          post-task: exec -- book:build
      - uses: actions/upload-pages-artifact@v5
        if: runner.os == 'Linux' && runner.arch == 'X64'
        with:
          path: packages/example-book/book
          retention-days: 3
    

  deploy-pages:
    needs:
      - build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
